robot:
  ip: "192.168.124.141"
  robot_program_name: "movement_robot"
  name: "movement_robot"

scanner:
  ip: "192.168.124.142"
  port: 6000
  name: "hikrobot_scanner"
  timeout: 2.5
  
lis:
  ip: "192.168.12.80"
  port: 7117